// <auto-generated />
using System;
using BuildSheets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuildSheets.Migrations
{
    [DbContext(typeof(BuildSheetsDBContext))]
    [Migration("20200111015856_InitialMigrationWithAllModels")]
    partial class InitialMigrationWithAllModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuildSheets.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Rev");

                    b.HasKey("Id");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("BuildSheets.Models.BoardBuildSheet", b =>
                {
                    b.Property<int>("BoardId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("BoardId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("BoardBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.BuildSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APN");

                    b.Property<string>("CustomerGateway");

                    b.Property<int?>("DeviceFirmwareId");

                    b.Property<string>("DeviceModemId");

                    b.Property<int?>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("DeviceFirmwareId");

                    b.HasIndex("DeviceModemId");

                    b.HasIndex("ProductId");

                    b.ToTable("BuildSheets");
                });

            modelBuilder.Entity("BuildSheets.Models.CertificationLabelRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ModemId");

                    b.Property<int>("Side");

                    b.HasKey("Id");

                    b.ToTable("CertificationLabelRequirement");
                });

            modelBuilder.Entity("BuildSheets.Models.CertificationLabelRequirementBuildSheet", b =>
                {
                    b.Property<int>("CertificationLabelRequirementId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("CertificationLabelRequirementId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("CertificationLabelRequirementBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.ContractManufactureAssemblyDrawing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Rev");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("ContractManufactureAssemblyDrawing");
                });

            modelBuilder.Entity("BuildSheets.Models.ContractManufactureAssemblyDrawingBuildSheet", b =>
                {
                    b.Property<int>("ContractManufactureAssemblyDrawingId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("ContractManufactureAssemblyDrawingId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("ContractManufactureAssemblyDrawingBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.DeviceFirmware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("DeviceFirmware");
                });

            modelBuilder.Entity("BuildSheets.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rev");

                    b.Property<DateTime>("RevDate");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("BuildSheets.Models.DocumentBuildSheet", b =>
                {
                    b.Property<int>("DocumentId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("DocumentId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("DocumentBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.GeotabAssemblyDrawing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Rev");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("GeotabAssemblyDrawing");
                });

            modelBuilder.Entity("BuildSheets.Models.GeotabAssemblyDrawingBuildSheet", b =>
                {
                    b.Property<int>("GeotabAssemblyDrawingId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("GeotabAssemblyDrawingId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("GeotabAssemblyDrawingBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Rev");

                    b.HasKey("Id");

                    b.ToTable("Hardware");
                });

            modelBuilder.Entity("BuildSheets.Models.HardwareBuildSheet", b =>
                {
                    b.Property<int>("HardwareId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("HardwareId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("HardwareBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.Insert", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Rev");

                    b.HasKey("Id");

                    b.ToTable("Insert");
                });

            modelBuilder.Entity("BuildSheets.Models.InsertBuildSheet", b =>
                {
                    b.Property<string>("InsertId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("InsertId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("InsertBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Rev");

                    b.HasKey("Id");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("BuildSheets.Models.LabelBuildSheet", b =>
                {
                    b.Property<int>("LabelId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("LabelId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("LabelBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.Modem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DefaultChannel");

                    b.Property<string>("FCC");

                    b.Property<string>("FirmwareRevision");

                    b.Property<string>("FirmwareVersion");

                    b.Property<int>("HardwareRevision");

                    b.Property<string>("HardwareVersion");

                    b.Property<string>("IC");

                    b.Property<string>("IMEIId");

                    b.Property<string>("IMEIRange");

                    b.HasKey("Id");

                    b.ToTable("Modem");
                });

            modelBuilder.Entity("BuildSheets.Models.Packaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Rev");

                    b.HasKey("Id");

                    b.ToTable("Packaging");
                });

            modelBuilder.Entity("BuildSheets.Models.PackagingBuildSheet", b =>
                {
                    b.Property<int>("PackagingId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("PackagingId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("PackagingBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Description");

                    b.Property<DateTime>("Launch");

                    b.Property<int>("MyProperty");

                    b.Property<string>("Owner");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BuildSheets.Models.TesterParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceName");

                    b.Property<string>("Parameter")
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("Id");

                    b.ToTable("TesterParameters");
                });

            modelBuilder.Entity("BuildSheets.Models.TesterSoftware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductCode");

                    b.Property<string>("ProductCodeURL");

                    b.Property<string>("TesterVersion");

                    b.Property<string>("TesterVersionURL");

                    b.HasKey("Id");

                    b.ToTable("TesterSoftware");
                });

            modelBuilder.Entity("BuildSheets.Models.TesterSoftwareBuildsheet", b =>
                {
                    b.Property<int>("TesterSoftwareId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("TesterSoftwareId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("TesterSoftwareBuildsheet");
                });

            modelBuilder.Entity("BuildSheets.Models.WorkInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocationId");

                    b.Property<string>("Name");

                    b.Property<string>("Rev");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("WorkInstruction");
                });

            modelBuilder.Entity("BuildSheets.Models.WorkInstructionBuildSheet", b =>
                {
                    b.Property<int>("WorkInstructionId");

                    b.Property<int>("BuildSheetId");

                    b.HasKey("WorkInstructionId", "BuildSheetId");

                    b.HasIndex("BuildSheetId");

                    b.ToTable("WorkInstructionBuildSheet");
                });

            modelBuilder.Entity("BuildSheets.Models.BoardBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.Board", "Board")
                        .WithMany("BoardBuildSheets")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("InternalSubAssemblyBoards")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.BuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.DeviceFirmware", "DeviceFirmware")
                        .WithMany()
                        .HasForeignKey("DeviceFirmwareId");

                    b.HasOne("BuildSheets.Models.Modem", "DeviceModem")
                        .WithMany()
                        .HasForeignKey("DeviceModemId");

                    b.HasOne("BuildSheets.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("BuildSheets.Models.CertificationLabelRequirementBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("CertificationLabelRequirements")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.CertificationLabelRequirement", "CertificationLabelRequirement")
                        .WithMany("CertificationLabelRequirementBuildSheets")
                        .HasForeignKey("CertificationLabelRequirementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.ContractManufactureAssemblyDrawingBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("ContractManufactureAssemblyDrawings")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.ContractManufactureAssemblyDrawing", "ContractManufactureAssemblyDrawing")
                        .WithMany("ContractManufactureAssemblyDrawingBuildSheets")
                        .HasForeignKey("ContractManufactureAssemblyDrawingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.DeviceFirmware", b =>
                {
                    b.HasOne("BuildSheets.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.DocumentBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("Documents")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.Document", "Document")
                        .WithMany("DocumentBuildSheets")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.GeotabAssemblyDrawingBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("GeotabAssemblyDrawings")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.GeotabAssemblyDrawing", "GeotabAssemblyDrawing")
                        .WithMany("GeotabAssemblyDrawingBuildSheets")
                        .HasForeignKey("GeotabAssemblyDrawingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.HardwareBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("OtherHardware")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.Hardware", "Hardware")
                        .WithMany("HardwareBuildSheets")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.InsertBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("Inserts")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.Insert", "Insert")
                        .WithMany("InsertBuildSheets")
                        .HasForeignKey("InsertId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.LabelBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("Labels")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.Label", "Label")
                        .WithMany("LabelBuildSheets")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.PackagingBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("Packagings")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.Packaging", "Packaging")
                        .WithMany("PackagingBuildSheets")
                        .HasForeignKey("PackagingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.TesterSoftwareBuildsheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("TesterSoftwares")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.TesterSoftware", "TesterSoftware")
                        .WithMany("TesterSoftwareBuildsheets")
                        .HasForeignKey("TesterSoftwareId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuildSheets.Models.WorkInstructionBuildSheet", b =>
                {
                    b.HasOne("BuildSheets.Models.BuildSheet", "BuildSheet")
                        .WithMany("WorkInstructions")
                        .HasForeignKey("BuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuildSheets.Models.WorkInstruction", "WorkInstruction")
                        .WithMany("WorkInstructionBuildSheets")
                        .HasForeignKey("WorkInstructionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
